'use client';
import {useState} from 'react';
import ClubHeader from '@/components/club-header';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {ArrowUpRight,CalendarDays,MapPin,Trophy,Heart,Users,ArrowRight} from 'lucide-react';
const teams=['Paraíso Fútbol','Los Pinos','Unión del Sur','Deportivo Norte'];
const games=[{date:'29 AGO',time:'Finalizado',home:0,away:1,score:[2,1],round:1},{date:'29 AGO',time:'Finalizado',home:2,away:3,score:[1,1],round:1},{date:'12 SEP',time:'10:00',home:3,away:0,score:null,round:2},{date:'12 SEP',time:'11:30',home:1,away:2,score:null,round:2},{date:'19 SEP',time:'10:00',home:0,away:2,score:null,round:3},{date:'19 SEP',time:'11:30',home:1,away:3,score:null,round:3}];
export default function Home(){
const [cat,setCat]=useState('Infantiles');const [round,setRound]=useState(2);
return <><ClubHeader/>
<main><section className="hero"><div className="herocopy"><p className="eyebrow"><span/> DEPORTE, ENCUENTRO Y FORMACIÓN</p><h1>Crecer en equipo.<br/><em>Jugar con el corazón.</em></h1><p>Un lugar para aprender, hacer amigos y disfrutar del fútbol. Dentro y fuera de la cancha.</p><a className="primary" href="/reservas">Reservá tu cancha <ArrowRight size={19}/></a><a className="textlink" href="/inscripciones">Inscribite a la escuelita ↗</a></div><div className="crest"><img src="/escudo.png" alt="El Paraíso: árbol, pelota y escudo verde"/><p>RAÍCES FUERTES. SUEÑOS GRANDES.</p></div></section>
<section className="quickaccess" aria-label="Servicios del club"><a href="/actividades"><span>01 / ACTIVIDADES</span><strong>Encontrá tu deporte ↗</strong><p>Fútbol, hockey, danza y gimnasio.</p></a><a href="/reservas"><span>02 / RESERVAS</span><strong>Nos vemos en la cancha ↗</strong><p>Consultá disponibilidad y reservá tu turno.</p></a><a href="/inscripciones"><span>03 / INSCRIPCIONES</span><strong>Sumate al equipo ↗</strong><p>Completá la ficha oficial del club.</p></a></section><section className="tournaments" id="torneos"><div className="sectiontop"><div><p className="eyebrow green">EL EQUIPO, SIEMPRE CERCA</p><h2>Nuestra cancha digital<span>.</span></h2><p>Fixture, resultados y próximas fechas para profes y familias.</p></div><span className="demo">Temporada de ejemplo · 2026</span></div>
<Tabs defaultValue="Infantiles" onValueChange={v=>setCat(String(v))}><TabsList className="categories">{['Infantiles','Juveniles'].map(c=><TabsTrigger key={c} value={c}>{c}</TabsTrigger>)}</TabsList>{['Infantiles','Juveniles'].map(c=><TabsContent key={c} value={c}><div className="dashboard"><aside className="next"><p className="eyebrow">PRÓXIMO ENCUENTRO</p><div className="matchmeta">Torneo Amistad · {cat}</div><div className="versus"><span className="opponent">DN</span><b>VS</b><img src="/escudo.png" alt="Paraíso Fútbol"/></div><div className="teamnames"><strong>Deportivo Norte</strong><strong>Paraíso Fútbol</strong></div><div className="nextdetails"><p><CalendarDays size={18}/> Sábado 12 de septiembre · {c==='Infantiles'?'10:00':'15:00'} h</p><p><MapPin size={18}/> Cancha de Deportivo Norte · Visitante</p></div><div className="reminder">Acompañemos con respeto.<br/>El mejor resultado es disfrutar juntos.</div></aside><div className="results"><Tabs defaultValue="fixture"><TabsList className="viewtabs" variant="line"><TabsTrigger value="fixture">Fixture</TabsTrigger><TabsTrigger value="posiciones">Posiciones</TabsTrigger></TabsList><TabsContent value="fixture"><div className="round"><button aria-label="Fecha anterior" disabled={round===1} onClick={()=>setRound(round-1)}>←</button><strong>Fecha {round} <span>de 3</span></strong><button aria-label="Fecha siguiente" disabled={round===3} onClick={()=>setRound(round+1)}>→</button></div>{games.filter(g=>g.round===round).map((g,i)=><div className="game" key={i}><div className="gamedate">{g.date}<span>{g.score?'Finalizado':(c==='Juveniles'?(i===0?'15:00':'16:30'):g.time)+' h'}</span></div><div className="gamepair"><span className={g.home===0?'ourteam':''}>{teams[g.home]}</span><b>{g.score?g.score.join(' – '):'vs'}</b><span className={g.away===0?'ourteam':''}>{teams[g.away]}</span></div><small>{g.score?'Resultado de ejemplo':'Sede: '+teams[g.home]}</small></div>)}<p className="footnote">Calendario ilustrativo. Fechas, horarios y sedes sujetos a confirmación.</p></TabsContent><TabsContent value="posiciones"><Table><TableHeader><TableRow>{['#','Equipo','PJ','G','E','P','DG','PTS'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{[[0,1,1,0,0,1,3],[2,1,0,1,0,0,1],[3,1,0,1,0,0,1],[1,1,0,0,1,-1,0]].map((r,i)=><TableRow className={r[0]===0?'highlight':''} key={i}><TableCell>{i+1}</TableCell><TableCell>{teams[r[0]]}</TableCell>{r.slice(1).map((n,j)=><TableCell key={j}>{n}</TableCell>)}</TableRow>)}</TableBody></Table><p className="footnote">3 puntos por victoria · 1 por empate · 0 por derrota.<br/>Datos ilustrativos, sin resultados oficiales cargados.</p></TabsContent></Tabs></div></div></TabsContent>)}</Tabs><p className="example">Los equipos, categorías y partidos de esta sección son ejemplos para mostrar el funcionamiento.</p></section>
<section id="escuela" className="school"><div><p className="eyebrow green">MÁS QUE FÚTBOL</p><h2>Una escuela.<br/>Muchos caminos<br/>por descubrir.</h2></div><div><p className="intro">En Paraíso Fútbol, el juego es el punto de partida para crecer.</p><p>Somos una escuelita de fútbol infantil y juvenil. Nuestra propuesta une la formación deportiva con el aprendizaje compartido, poniendo a cada chico y chica en el centro.</p><div className="values" id="formacion"><article><Heart/><h3>Disfrutar y aprender</h3><p>El juego, la confianza y el progreso personal como protagonistas.</p></article><article><Users/><h3>Ser parte de un equipo</h3><p>Compañerismo, inclusión y respeto por quienes comparten la cancha.</p></article><article><Trophy/><h3>Competir con valores</h3><p>Aprender de cada encuentro, acompañar y celebrar el esfuerzo.</p></article></div></div></section>
<section id="familias" className="families"><div><p className="eyebrow">DEL MISMO LADO DE LA CANCHA</p><h2>Las familias también<br/>somos parte del equipo.</h2></div><div><p>Consultá el fixture antes de cada encuentro y confirmá con el profe el horario de llegada y la sede.</p><p className="pending">Inscribite desde la ficha oficial y consultá los horarios de entrenamiento con el club al 11 4915-3094.</p><a href="#torneos">Consultar próximas fechas <ArrowUpRight size={20}/></a></div></section></main><footer><a className="brand" href="#"><img src="/escudo.png" alt=""/><span>PARAÍSO FÚTBOL</span></a><p>Aprender. Compartir. Jugar.</p><a href="https://wa.me/5491149153094" target="_blank" rel="noopener noreferrer">WhatsApp · 11 4915-3094 ↗</a><a href="/gestion">Gestión del club</a></footer></>}
