import {RecoveryPage,isRecovery} from './recovery';
import React from 'react';
import {createRoot} from 'react-dom/client';
import Home from '../app/page';
import Activities from '../app/actividades/page';
import Bookings from '../app/reservas/page';
import Admin from '../app/gestion/page';
import {AccessGate,LoginPage,AccountPage,PendingRegistration} from './accounts';
import {restoreSession} from './auth';
import {InstallApp} from './install';
const routes:Record<string,React.ComponentType>={'/':Home,'/actividades':Activities,'/reservas':()=> <AccessGate roles={['admin','family']}><Bookings/></AccessGate>,'/inscripciones':PendingRegistration,'/gestion':()=> <AccessGate roles={['admin']}><Admin/></AccessGate>,'/login':LoginPage,'/mi-cuenta':AccountPage};
const Page=isRecovery||new URLSearchParams(location.search).has('recuperar')?RecoveryPage:routes[location.pathname]||Home;
const root=createRoot(document.getElementById('root')!);
root.render(<p role="status">Conectando con tu cuenta…</p>);
let sessionError='';
restoreSession().catch(error=>{sessionError=error.message;}).finally(()=>root.render(<><div className="pilotbar"><strong>Paraíso Fútbol · Desarrollo</strong><span>Reservas en la nube. Solo datos ficticios; sin cobros reales.</span><a href="/mi-cuenta">Mi espacio ↗</a></div>{sessionError&&<p className="notice" role="alert">No pudimos recuperar tu acceso: {sessionError} Volvé a ingresar o revisá tu conexión.</p>}<InstallApp/><Page/></>));
if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js');
