import {useEffect,useState,type FormEvent} from 'react';
import {backend,rpc,tenantId} from './backend';
import {currentUser,roleNames} from './auth';
import {randomId} from '../../../../public/src/core/id.js';
import {continueCampaign} from './group-dispatch.mjs';
const money=(value:number)=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS'}).format(value);
const periodNow=()=>{const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Argentina/Buenos_Aires',year:'numeric',month:'2-digit'}).formatToParts(new Date());return parts.find(p=>p.type==='year')!.value+'-'+parts.find(p=>p.type==='month')!.value;};
const status=(due:any)=>!due?'Sin cuota':Number(due.paid)>=Number(due.amount)?'Al día':Number(due.paid)>0?'Pago parcial':'Pendiente';
const labels:Record<string,string>={accepted:'Aceptado por push',partial:'Aceptado parcialmente',no_devices:'En bandeja, sin dispositivos',failed:'Push fallido',sending:'Resultado sin confirmar'};
async function list(table:string,query=''){return backend.request(`/rest/v1/${table}?tenant_id=eq.${tenantId}&select=*${query}`);}
export function PeopleAdmin(){
 const [members,setMembers]=useState<any[]>([]),[access,setAccess]=useState<any>(null);
 const [people,setPeople]=useState<any[]>([]),[tags,setTags]=useState<any[]>([]),[links,setLinks]=useState<any[]>([]),[dues,setDues]=useState<any[]>([]),[campaigns,setCampaigns]=useState<any[]>([]);
 const [period,setPeriod]=useState(periodNow()),[search,setSearch]=useState(''),[tag,setTag]=useState(''),[payment,setPayment]=useState(''),[editor,setEditor]=useState<any>(null),[selected,setSelected]=useState<string[]>([]),[fee,setFee]=useState<any>(null),[audit,setAudit]=useState<any[]>([]);
 const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[campaign,setCampaign]=useState<any>(null),[progress,setProgress]=useState<any[]>([]);
 async function load(){const [p,t,l,d,c,m]=await Promise.all([list('club_people','&order=name'),list('club_tags','&order=name'),list('club_person_tags'),list('club_dues',`&period=eq.${period}-01`),list('club_campaigns','&order=created_at.desc&limit=20'),list('club_members')]);setMembers(m);setPeople(p);setTags(t);setLinks(l);setDues(d);setCampaigns(c);setLoaded(true);}
 useEffect(()=>{setLoaded(false);void load().catch(e=>setError(e.message));},[period]);
 async function action(work:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await work();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const dueFor=(id:string)=>dues.find(d=>d.person_id===id);
 const filtered=people.filter(p=>(p.name+' '+p.email+' '+p.phone).toLowerCase().includes(search.toLowerCase())&&(!tag||links.some(l=>l.person_id===p.id&&l.tag_id===tag))&&(!payment||status(dueFor(p.id))===payment));
 const targets=people.filter(p=>p.active&&p.user_id&&members.some(m=>m.user_id===p.user_id)&&links.some(l=>l.person_id===p.id&&l.tag_id===tag));
 async function savePerson(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);await action(async()=>{await rpc('club_save_person',{p_id:editor.id||null,p_name:data.get('name'),p_email:data.get('email'),p_phone:data.get('phone'),p_active:data.get('active')==='on',p_tags:selected});setEditor(null);await load();setMessage('Ficha guardada.');});}
 async function saveFee(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);await action(async()=>{await rpc('club_save_due',{p_person:fee.person.id,p_period:fee.period+'-01',p_amount:Number(data.get('amount')),p_paid:Number(data.get('paid')),p_note:data.get('note'),p_expected:fee.due?.updated_at||null});setFee(null);await load();setMessage('Cuota actualizada. El cambio quedó registrado en el historial.');});}
 async function showCampaign(c:any){setCampaign(c);setProgress(await rpc('club_campaign_progress',{p_campaign:c.id}));}
 async function dispatch(c:any){
  setCampaign(c);
  const {errors,firstError}=await continueCampaign(c,{read:(id:string)=>rpc('club_campaign_progress',{p_campaign:id}),send:(payload:any)=>backend.localRequest('/api/push/send',payload),onProgress:setProgress});
  if(firstError)setError(firstError);
  await load();setMessage(errors?`Hubo errores en ${errors} destinatario(s). Consultá resultados y continuá los que sigan sin procesar. Los resultados sin confirmar no se repiten.`:'Proceso terminado. Revisá el resultado por persona; aceptación no confirma recepción.');
 }
 async function createCampaign(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);await action(async()=>{const c={id:randomId(),title:String(data.get('title')),body:String(data.get('body')),created_by:currentUser()!.id};await rpc('club_create_campaign',{p_id:c.id,p_tag:tag,p_title:c.title,p_body:c.body});await load();await dispatch(c);});}
 return <section className="formcard" id="personas"><h2>Personas, cuotas y grupos</h2><p>Registro administrativo en pesos. No procesa cobros ni emite facturas. Las fichas nuevas no crean automáticamente una cuenta de acceso.</p>
 {error&&<p role="alert" className="formerror">{error}</p>}{message&&<p role="status" className="notice">{message}</p>}
 <div className="activityactions"><button disabled={busy} className="secondarybutton" onClick={()=>void action(load)}>Actualizar panel</button><button disabled={busy||!loaded} className="primary" onClick={()=>{setEditor({name:'',email:'',phone:'',active:true});setSelected([]);}}>Agregar persona</button></div>
 <div className="management-filters"><label className="field">Buscar persona<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nombre, correo o teléfono"/></label><label className="field">Mes de la cuota<input type="month" value={period} disabled={busy||!!fee||!loaded} onChange={e=>{if(e.target.value)setPeriod(e.target.value);}}/></label><label className="field">Grupo / etiqueta<select value={tag} disabled={busy} onChange={e=>setTag(e.target.value)}><option value="">Todas las personas</option>{tags.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label className="field">Estado de pago<select value={payment} onChange={e=>setPayment(e.target.value)}><option value="">Todos los estados</option>{['Sin cuota','Pendiente','Pago parcial','Al día'].map(s=><option key={s}>{s}</option>)}</select></label></div>
 <form className="management-inline" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const name=String(new FormData(form).get('tag'));void action(async()=>{await rpc('club_save_tag',{p_name:name});form.reset();await load();setMessage('Etiqueta creada. Asignala desde la ficha de cada persona.');});}}><label className="field">Nueva etiqueta<input name="tag" required maxLength={60} placeholder="Ej.: Sub 12, Familias, Hockey"/></label><button className="secondarybutton" disabled={busy||!loaded}>Crear etiqueta</button></form>
 {editor&&<form key={editor.id||"new"} className="formcard" onSubmit={savePerson}><h3>{editor.id?'Editar ficha':'Nueva persona'}</h3><label className="field">Nombre<input name="name" defaultValue={editor.name} required minLength={2} maxLength={120}/></label><label className="field">Correo de contacto<input name="email" type="email" defaultValue={editor.email} maxLength={254}/></label><label className="field">Teléfono<input name="phone" defaultValue={editor.phone} maxLength={40}/></label><label><input name="active" type="checkbox" defaultChecked={editor.active}/> Incluir en envíos grupales (no modifica el acceso al login)</label><fieldset><legend>Etiquetas</legend>{tags.map(t=><label className="management-tag" key={t.id}><input type="checkbox" checked={selected.includes(t.id)} onChange={e=>setSelected(e.target.checked?[...selected,t.id]:selected.filter(id=>id!==t.id))}/>{t.name}</label>)}</fieldset><p>El correo de contacto no cambia el correo de acceso de una cuenta existente.</p><button className="primary" disabled={busy}>Guardar ficha</button> <button type="button" disabled={busy} className="secondarybutton" onClick={()=>setEditor(null)}>Cancelar edición</button></form>}
 {loaded?<><p>{filtered.length} personas · Saldo del filtro: <strong>{money(filtered.reduce((sum,p)=>{const d=dueFor(p.id);return sum+(d?Number(d.amount)-Number(d.paid):0);},0))}</strong></p><div className="management-table"><table><thead><tr><th>Persona</th><th>Grupos</th><th>Cuota {period}</th><th>Acciones</th></tr></thead><tbody>{filtered.map(p=>{const due=dueFor(p.id);return <tr key={p.id}><td><strong>{p.name}</strong><small>{p.email||'Sin correo'} · {p.phone||'Sin teléfono'}</small><small>{members.some(m=>m.user_id===p.user_id)?'Acceso habilitado: '+roleNames[members.find(m=>m.user_id===p.user_id).role as keyof typeof roleNames]:p.user_id?'Acceso deshabilitado':'Sin cuenta de acceso'} · {p.active?'Incluida en grupos':'Excluida de envíos grupales'}</small></td><td>{tags.filter(t=>links.some(l=>l.person_id===p.id&&l.tag_id===t.id)).map(t=>t.name).join(', ')||'Sin etiquetas'}</td><td>{status(due)}{due&&<small>Cuota {money(Number(due.amount))} · Abonado {money(Number(due.paid))} · Saldo {money(Number(due.amount)-Number(due.paid))}</small>}</td><td><button className="secondarybutton" disabled={busy} onClick={()=>{setEditor(p);setSelected(links.filter(l=>l.person_id===p.id).map(l=>l.tag_id));}}>Editar {p.name}</button><button className="secondarybutton" disabled={busy} onClick={()=>void action(async()=>{setFee({person:p,due,period});setAudit(await list('club_due_audit',`&person_id=eq.${p.id}&period=eq.${period}-01&order=created_at.desc&limit=10`));})}>Cuota de {p.name}</button><button className="secondarybutton" disabled={busy||p.user_id===currentUser()?.id} onClick={()=>setAccess(p)}>Acceso de {p.name}</button></td></tr>;})}</tbody></table></div></>:<p role="status">Cargando registros…</p>}
 {access&&<form key={access.id} className="formcard" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);void action(async()=>{await rpc('club_person_access',{p_person:access.id,p_role:data.get('role'),p_enabled:data.get('enabled')==='on'});setAccess(null);await load();setMessage('Acceso actualizado.');});}}><h3>Acceso de {access.name}</h3><p>Vincula una cuenta existente en Supabase Auth. Para una ficha sin cuenta, se busca por su correo de contacto. No envía correos ni crea contraseñas.</p><label className="field">Perfil<select name="role" defaultValue={members.find(m=>m.user_id===access.user_id)?.role||'family'}>{Object.entries(roleNames).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label><input name="enabled" type="checkbox" defaultChecked={members.some(m=>m.user_id===access.user_id)}/> Permitir acceso al club</label><p>Deshabilitar el acceso también desactiva los dispositivos de notificaciones de esta cuenta en el club.</p><button className="primary" disabled={busy}>Guardar acceso</button> <button type="button" className="secondarybutton" disabled={busy} onClick={()=>setAccess(null)}>Cerrar acceso</button></form>}
 {fee&&<form key={fee.person.id+fee.period} className="formcard" onSubmit={saveFee}><h3>Cuota de {fee.person.name} · {fee.period}</h3><label className="field">Importe de la cuota (ARS)<input name="amount" type="number" min="0" max="100000000" step="0.01" required defaultValue={fee.due?.amount??''}/></label><label className="field">Total abonado a la fecha (ARS)<input name="paid" type="number" min="0" max="100000000" step="0.01" required defaultValue={fee.due?.paid??0}/></label><label className="field">Nota / referencia<input name="note" maxLength={300} defaultValue={fee.due?.note||''}/></label><p>Ingresá el total acumulado abonado, no solo el último pago.</p><button className="primary" disabled={busy}>Guardar cuota</button> <button type="button" className="secondarybutton" disabled={busy} onClick={()=>setFee(null)}>Cerrar cuota</button><h4>Últimos cambios</h4>{audit.map(a=><p key={a.id}>{new Date(a.created_at).toLocaleString('es-AR',{timeZone:'America/Argentina/Buenos_Aires'})} · {members.find(m=>m.user_id===a.created_by)?.display_name||'Administrador'} · Cuota {money(Number(a.after_value.amount))} · Abonado {money(Number(a.after_value.paid))} · {a.after_value.note}</p>)}</form>}
 <h3>Enviar aviso al grupo</h3><p>Elegí una etiqueta arriba. El envío incluye a todas sus personas activas con cuenta vinculada, sin aplicar el filtro de búsqueda o de pago. Máximo 50 por envío. Conservá esta página abierta mientras se envía.</p>
 {tag&&<form className="formcard" onSubmit={createCampaign}><p><strong>{tags.find(t=>t.id===tag)?.name}: {targets.length} destinatarios con cuenta</strong>. Las personas sin cuenta no pueden recibir avisos.</p><details><summary>Ver destinatarios antes de enviar</summary><ul>{targets.map(p=><li key={p.id}>{p.name}</li>)}</ul></details><label className="field">Título del aviso grupal<input name="title" maxLength={80} required/></label><label className="field">Mensaje al grupo<textarea name="body" maxLength={240} rows={3} required/></label><p>El mensaje puede aparecer en la pantalla bloqueada. No incluyas datos privados de pagos individuales.</p><button className="primary" disabled={busy||!loaded||targets.length===0||targets.length>50}>{busy?'Procesando…':`Enviar al grupo (${targets.length})`}</button></form>}
 {campaign&&<section className="formcard"><h4>{campaign.title}</h4><button className="secondarybutton" disabled={busy} onClick={()=>void action(()=>showCampaign(campaign))}>Consultar resultados</button>{campaign.created_by===currentUser()?.id&&<button className="secondarybutton" disabled={busy} onClick={()=>void action(()=>dispatch(campaign))}>Continuar destinatarios sin procesar</button>}<ul>{progress.map(p=><li key={p.request_id}>{p.name}: {p.status?labels[p.status]:'Sin procesar'}{p.status?` · ${p.accepted||0} dispositivo(s) aceptados`:''}</li>)}</ul><p>Los envíos registrados, incluidos los resultados sin confirmar, no se repiten al continuar.</p></section>}
 <h3>Historial de envíos grupales</h3>{campaigns.map(c=><p key={c.id}><button className="secondarybutton" disabled={busy} onClick={()=>void action(()=>showCampaign(c))}>{c.title} · {new Date(c.created_at).toLocaleString('es-AR')}</button></p>)}
 </section>;
}
