import {useState} from 'react';
import {useSchool,Card,Empty,Badge,Editor,selectField,choiceField,save,type Field} from './shared';
import {localDay,money,chargeState,chargeBalance,paidAmount} from './metrics.mjs';
import {receiptDocument} from './receipt.mjs';
export function Finance(){
 const c=useSchool(),d=c.data,[month,setMonth]=useState(localDay().slice(0,7)),[filter,setFilter]=useState(''),[editor,setEditor]=useState<any>(null),[student,setStudent]=useState(''),[tab,setTab]=useState('cuotas');
 const charges=d.school_charges.filter(ch=>ch.period.startsWith(month)&&(!student||ch.student_id===student)&&(!filter||chargeState(ch,d.school_payments)===filter));
 const payments=d.school_payments.filter(p=>p.date.startsWith(month)&&(!student||d.school_charges.find(ch=>ch.id===p.charge_id)?.student_id===student));
 const expenses=d.school_expenses.filter(e=>e.date.startsWith(month));
 const incoming=payments.filter(p=>!p.voided_at).reduce((n,p)=>n+Number(p.amount),0),outgoing=expenses.reduce((n,e)=>n+Number(e.amount),0);
 const fields:Record<string,Field[]>={
 charge:[selectField('student_id','Alumno',d.school_students.filter(s=>s.active)),choiceField('kind','Tipo de cargo',['Cuota','Matrícula']),{name:'month',label:'Mes / temporada de matrícula',type:'month',required:true},{name:'due_date',label:'Vencimiento',type:'date',required:true},{name:'amount',label:'Importe (ARS)',type:'number',min:0.01,max:100000000,step:'0.01',required:true},{name:'concept',label:'Concepto (ej.: cuota o matrícula + uniforme)',required:true,maxLength:200}],
 payment:[{name:'date',label:'Fecha del pago',type:'date',required:true,max:localDay()},{name:'amount',label:'Importe recibido en este pago (ARS)',type:'number',min:0.01,max:editor?.row?.balance||100000000,step:'0.01',required:true},choiceField('method','Medio de pago',['Efectivo','Transferencia','Tarjeta']),{name:'reference',label:'Referencia / comprobante',maxLength:200}],
 expense:[{name:'date',label:'Fecha del gasto',type:'date',required:true},{name:'concept',label:'Concepto',required:true,maxLength:200},choiceField('category','Rubro',['Personal','Alquiler','Materiales','Otro']),{name:'amount',label:'Importe del gasto (ARS)',type:'number',min:0.01,max:100000000,step:'0.01',required:true},choiceField('method','Medio de pago',['Efectivo','Transferencia','Tarjeta'])],
 void_payment:[{name:'reason',label:'Motivo de anulación (conserva historial)',required:true,maxLength:300}]
 };
 function receipt(p:any){const ch=d.school_charges.find(ch=>ch.id===p.charge_id),s=d.school_students.find(s=>s.id===ch.student_id),t=d.school_tutors.find(t=>t.id===s.tutor_id);receiptDocument({payment:p,charge:ch,student:s,tutor:t}).save('recibo-'+p.id+'.pdf');}
 return <><div className="sc-section-intro"><div><span className="sc-overline">FINANZAS</span><h1>Cuentas y cobranzas</h1><p>Cuotas, matriculación y movimientos en pesos argentinos.</p></div><button className="sc-primary" onClick={()=>setEditor({kind:'charge',row:{kind:'Cuota',month,due_date:month+'-10',concept:'Cuota mensual'}})}>+ Generar cuota o matrícula</button></div>
 <div className="sc-notice">Registro administrativo de pagos. No procesa tarjetas ni transferencias. Las cuotas antiguas por persona se conservan en «Cuentas y etiquetas»; no se duplicaron como cargos de alumnos.</div>
 <div className="sc-toolbar"><label>Mes<input type="month" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value);}}/></label><label>Alumno<select value={student} onChange={e=>setStudent(e.target.value)}><option value="">Todos</option>{d.school_students.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Semáforo<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Todos los estados</option><option>Al día</option><option>Pendiente</option><option>Deudor</option></select></label></div>
 <div className="sc-finance-strip"><div><small>Ingresos cobrados · filtro de alumno</small><strong>{money(incoming)}</strong></div><div><small>Egresos del club · mes</small><strong>{money(outgoing)}</strong></div><div><small>Saldo pendiente · cargos filtrados</small><strong>{money(charges.reduce((n,ch)=>n+chargeBalance(ch,d.school_payments),0))}</strong></div></div>
 <div className="sc-tabs">{[['cuotas','Cuotas y matrículas'],['pagos','Historial de pagos'],['gastos','Gastos']].map(([key,label])=><button key={key} aria-pressed={tab===key} onClick={()=>setTab(key)}>{label}</button>)}</div>
 {editor&&<Editor key={editor.kind+(editor.row.id||editor.row.charge_id||'new')} title={editor.kind==='charge'?'Nuevo cargo':editor.kind==='payment'?'Registrar pago':editor.kind==='expense'?'Registrar gasto':'Anular pago'} fields={fields[editor.kind]} initial={editor.row} onClose={()=>setEditor(null)} onSave={async row=>{await save(editor.kind,editor.kind==='charge'?{...row,period:row.month+'-01'}:row);}}/>}
 {tab==='cuotas'&&<Card title="Estado de cuenta por alumno"><p className="sc-hint">Verde: cancelado · Amarillo: saldo dentro del plazo · Rojo: saldo vencido. Las cuotas sin generar no se consideran deuda.</p><div className="sc-table-wrap"><table><thead><tr><th>Alumno / concepto</th><th>Vence</th><th>Importe</th><th>Abonado</th><th>Saldo</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{charges.map(ch=>{const state=chargeState(ch,d.school_payments),balance=chargeBalance(ch,d.school_payments);return <tr key={ch.id}><td><strong>{d.school_students.find(s=>s.id===ch.student_id)?.name}</strong><small>{ch.concept} · {ch.kind}</small></td><td>{ch.due_date}</td><td>{money(ch.amount)}</td><td>{money(paidAmount(ch.id,d.school_payments))}</td><td><strong>{money(balance)}</strong></td><td><Badge tone={state==='Al día'?'green':state==='Deudor'?'red':'amber'}>{state}</Badge></td><td><button className="sc-quiet" disabled={balance<=0} onClick={()=>setEditor({kind:'payment',row:{charge_id:ch.id,date:localDay(),amount:balance,balance,method:'Efectivo'}})}>Registrar pago de {d.school_students.find(s=>s.id===ch.student_id)?.name}</button></td></tr>;})}</tbody></table></div>{!charges.length&&<Empty>No hay cargos para este mes y filtro. Creá una cuota o matrícula para comenzar.</Empty>}</Card>}
 {tab==='pagos'&&<Card title="Ingresos registrados"><div className="sc-table-wrap"><table><thead><tr><th>Fecha</th><th>Alumno</th><th>Medio</th><th>Importe</th><th>Recibo</th></tr></thead><tbody>{payments.map(p=><tr key={p.id}><td>{p.date}</td><td>{d.school_students.find(s=>s.id===d.school_charges.find(ch=>ch.id===p.charge_id)?.student_id)?.name}<small>{p.reference}</small></td><td>{p.method}{p.voided_at&&<Badge tone="red">Anulado</Badge>}</td><td>{money(p.amount)}</td><td><button className="sc-quiet" onClick={()=>receipt(p)}>Descargar recibo PDF</button>{!p.voided_at&&<button className="sc-quiet" onClick={()=>setEditor({kind:'void_payment',row:p})}>Anular con motivo</button>}</td></tr>)}</tbody></table></div>{!payments.length&&<Empty>Los pagos aparecerán aquí con su recibo descargable.</Empty>}</Card>}
 {tab==='gastos'&&<Card title="Egresos del club" action={<button className="sc-primary" onClick={()=>setEditor({kind:'expense',row:{date:localDay(),category:'Materiales',method:'Efectivo'}})}>+ Registrar gasto</button>}><div className="sc-table-wrap"><table><thead><tr><th>Fecha</th><th>Concepto</th><th>Rubro</th><th>Medio</th><th>Importe</th></tr></thead><tbody>{expenses.map(e=><tr key={e.id}><td>{e.date}</td><td>{e.concept}</td><td>{e.category}</td><td>{e.method}</td><td>{money(e.amount)}</td></tr>)}</tbody></table></div>{!expenses.length&&<Empty>No hay egresos registrados este mes.</Empty>}</Card>}
 </>;
}
