import {useState} from 'react';
import {useSchool,Card,Empty,Badge,Editor,save,selectField,choiceField,type Field} from './shared';
import {localDay,clock,minutes} from './metrics.mjs';
import {backend,rpc} from '../backend';
import {continueCampaign} from '../group-dispatch.mjs';
import {randomId} from '../../../../../public/src/core/id.js';

export function Matches(){
 const c=useSchool(),d=c.data,[editor,setEditor]=useState<any>(null),[selected,setSelected]=useState('');
 const matches=[...d.school_matches].sort((a,b)=>b.date.localeCompare(a.date)||a.start_min-b.start_min),match=matches.find(m=>m.id===selected);
 const fields:Field[]=[selectField('category_id','Categoría',d.school_categories.filter(x=>x.active)),{name:'date',label:'Fecha',type:'date',required:true},{name:'start',label:'Hora',type:'time',required:true},{name:'opponent',label:'Rival',required:true,maxLength:120},{name:'venue',label:'Cancha / dirección',required:true,maxLength:200},choiceField('side','Condición',['Local','Visitante']),choiceField('status','Estado',['Programado','Jugado','Cancelado'])];
 return <><div className="sc-section-heading"><div><h2>Partidos y convocatorias</h2><p>Organizá los encuentros y el seguimiento deportivo de cada jugador.</p></div>{c.admin&&<button className="sc-primary" onClick={()=>setEditor({date:localDay(),start:'10:00',side:'Local',status:'Programado'})}>+ Nuevo partido</button>}</div>
 {editor&&<Editor key={editor.id||'new'} title={editor.id?'Editar partido':'Nuevo partido'} initial={editor} fields={fields} onClose={()=>setEditor(null)} onSave={async v=>{await save('match',{...v,start_min:minutes(v.start)});}}/>}
 <div className="sc-split"><Card title="Calendario de encuentros">{matches.length?matches.map(m=><div className={'sc-match '+(selected===m.id?'selected':'')} key={m.id}><button className="sc-match-select" onClick={()=>setSelected(m.id)}><small>{m.date} · {clock(m.start_min)} · {m.side}</small><strong>vs {m.opponent}</strong><span>{d.school_categories.find(x=>x.id===m.category_id)?.name} · {m.venue}</span><Badge tone={m.status==='Cancelado'?'danger':m.status==='Jugado'?'success':'neutral'}>{m.status}</Badge></button>{c.admin&&<button className="sc-quiet" onClick={()=>setEditor({...m,start:clock(m.start_min)})}>Editar partido</button>}</div>):<Empty>Todavía no hay partidos programados.</Empty>}</Card>
 {match?<Roster key={match.id} match={match}/>:<Card title="Lista de convocados"><Empty>Seleccioná un partido para armar la convocatoria.</Empty></Card>}</div></>;
}
function Roster({match}:{match:any}){
 const c=useSchool(),d=c.data,[editing,setEditing]=useState<any>(null),[campaign,setCampaign]=useState<any>(null),[progress,setProgress]=useState<any[]>([]),[requestId]=useState(randomId);
 const calls=d.school_callups.filter(x=>x.match_id===match.id),students=d.school_students.filter(x=>x.category_id===match.category_id&&x.active),locked=match.status==='Cancelado';
 const tutorIds=new Set(calls.map(x=>d.school_students.find(s=>s.id===x.student_id)?.tutor_id));
 const people=d.club_people.filter(p=>p.active&&p.user_id&&d.club_members.some(m=>m.user_id===p.user_id)&&d.school_tutors.some(t=>tutorIds.has(t.id)&&t.person_id===p.id));
 const withoutAccount=[...tutorIds].filter(id=>!d.school_tutors.some(t=>t.id===id&&people.some(p=>p.id===t.person_id))).length;
 async function dispatch(cp:any){setCampaign(cp);const result=await continueCampaign(cp,{read:(id:string)=>rpc('club_campaign_progress',{p_campaign:id}),send:(payload:any)=>backend.localRequest('/api/push/send',payload),onProgress:setProgress});if(result.errors)throw Error(result.firstError||'Revisá los resultados antes de continuar.');c.notice('Envío procesado. Revisá los resultados: aceptación por push no confirma recepción.');}
 const labels:Record<string,string>={accepted:'Aceptado por push',partial:'Aceptado parcialmente',no_devices:'En bandeja, sin dispositivos',failed:'Push fallido',sending:'Sin confirmar'};
 return <Card title={'Convocados · '+calls.length}><p>Marcá los jugadores citados. Las estadísticas se cargan cuando el partido figure como jugado.</p>
 {students.map(s=>{const row=calls.find(x=>x.student_id===s.id);return <div className="sc-list-row" key={s.id}><label className="sc-check"><input type="checkbox" checked={!!row} disabled={c.busy||locked} onChange={e=>{const remove=!e.target.checked;void c.run(async()=>{await save('callup',{match_id:match.id,student_id:s.id,remove});await c.refresh();});}}/>{s.name}</label>{row&&<div><small>{row.goals} goles · {row.assists} asist. · {row.minutes} min · {row.yellow} amar. · {row.red} rojas</small><button className="sc-quiet" disabled={c.busy||locked||match.status!=='Jugado'} onClick={()=>setEditing(row)}>Estadísticas</button></div>}</div>;})}
 {!students.length&&<Empty>No hay alumnos activos en esta categoría.</Empty>}
 {editing&&<Editor key={editing.student_id} title="Estadísticas del jugador" initial={editing} fields={['goals','assists','minutes','yellow','red'].map((name,i)=>({name,label:['Goles','Asistencias','Minutos','Amarillas','Rojas'][i],type:'number',required:true,min:0,max:[50,50,180,2,1][i],step:'1'}))} onClose={()=>setEditing(null)} onSave={async v=>{await save('callup',v);}}/>}
 {c.admin&&<div className="sc-callout"><h3>Avisar a los tutores</h3><p>{people.length} cuentas vinculadas · {withoutAccount} tutores sin cuenta habilitada. El aviso incluye rival, fecha, hora y lugar. Cada tutor recibe un aviso aunque tenga más de un hijo convocado.</p><details><summary>Revisar destinatarios</summary><ul>{people.map(p=><li key={p.id}>{p.name}</li>)}</ul></details><p>Para recibirlo en el celular, el tutor debe haber activado notificaciones. Mantené esta página abierta durante el envío.</p><button className="sc-primary" disabled={c.busy||!!campaign||match.status!=='Programado'||!people.length||people.length>50} onClick={()=>void c.run(async()=>{const id=await rpc('school_match_campaign',{p_match:match.id,p_request:requestId});const rows=await backend.request('/rest/v1/club_campaigns?id=eq.'+id+'&select=*');if(!rows[0])throw Error('No se pudo recuperar el envío. Consultá el historial de grupos.');await dispatch(rows[0]);})}>Enviar convocatoria a {people.length} tutores</button>
 {campaign&&<><button disabled={c.busy} className="sc-quiet" onClick={()=>void c.run(async()=>{setProgress(await rpc('club_campaign_progress',{p_campaign:campaign.id}));})}>Actualizar resultados</button><button disabled={c.busy} className="sc-quiet" onClick={()=>void c.run(()=>dispatch(campaign))}>Continuar sin procesar</button><ul>{progress.map(p=><li key={p.request_id}>{p.name}: {labels[p.status]||'Sin procesar'}</li>)}</ul></>}
 <p><small>Los envíos quedan en el historial de Cuentas y etiquetas. Continuar nunca repite destinatarios ya registrados.</small></p></div>}
 </Card>;
}
