import {Users,Shirt,MapPin,CalendarDays,ChevronRight} from 'lucide-react';
import {useSchool,Card,Empty,Badge} from './shared';
import {attendanceSummary,chargeBalance,chargeState,clock,localDay,money} from './metrics.mjs';
export function Overview(){
 const {data:d,go}=useSchool(),today=localDay(),month=today.slice(0,7),sessions=d.school_sessions.filter(s=>s.date===today&&!s.cancelled).sort((a,b)=>a.start_min-b.start_min),attendance=attendanceSummary(d.school_attendance,d.school_sessions,month);
 const overdue=d.school_charges.filter(ch=>ch.kind==='Cuota'&&ch.period.startsWith(month)&&chargeState(ch,d.school_payments,today)==='Deudor');
 const students=d.school_students.filter(s=>s.active),courts=new Set(d.club_bookings.filter(b=>b.date===today&&b.status==='confirmada').map(b=>b.court));
 const stats=[{label:'Alumnos activos',value:students.length,detail:'En el padrón de la escuela',icon:Users,to:'alumnos'},{label:'Profesores activos',value:d.school_staff.filter(p=>p.active).length,detail:'Integrantes del equipo',icon:Shirt,to:'profesores'},{label:'Canchas ocupadas hoy',value:courts.size,detail:'Con reservas confirmadas',icon:MapPin,to:'reservas'},{label:'Asistencia del mes',value:attendance.percent===null?'—':attendance.percent+'%',detail:attendance.present+' presentes · '+attendance.absent+' ausentes',icon:CalendarDays,to:'entrenamientos'}];
 const delinquent=[...new Set(overdue.map(ch=>ch.student_id))];
 return <><div className="sc-section-intro"><div><span className="sc-overline">EL DÍA A DÍA DE TU CLUB</span><h1>Todo tu equipo, en un lugar.</h1><p>{new Date(today+'T12:00:00Z').toLocaleDateString('es-AR',{weekday:'long',day:'numeric',month:'long',timeZone:'UTC'})} · Temporada {today.slice(0,4)}</p></div><button className="sc-primary" onClick={()=>go('alumnos')}>Gestionar alumnos <ChevronRight size={16}/></button></div>
 <div className="sc-kpis">{stats.map(({label,value,detail,icon:Icon,to})=><button className="sc-kpi" key={label} onClick={()=>go(to)}><div><span>{label}</span><Icon size={20}/></div><strong>{value}</strong><small>{detail}</small></button>)}</div><p className="sc-hint">Asistencia: presentes ÷ (presentes + ausentes). Justificados y alumnos sin marcar no entran en el porcentaje.</p>
 <div className="sc-overview-grid"><Card title="Agenda de hoy" action={<button className="sc-quiet" onClick={()=>go('entrenamientos')}>Ver semana ↗</button>}>{sessions.length?sessions.map(s=><div className="sc-agenda" key={s.id}><time>{clock(s.start_min)}<small>{clock(s.end_min)}</small></time><div><strong>{d.school_categories.find(c=>c.id===s.category_id)?.name}</strong><p>{d.school_staff.find(p=>p.id===s.staff_id)?.name} · {s.court||'Cancha por definir'}</p><Badge tone={s.plan?'green':'amber'}>{s.plan?'Plan preparado':'Plan pendiente'}</Badge></div><button className="sc-quiet" onClick={()=>go('entrenamientos')}>Abrir →</button></div>):<Empty>No hay categorías con entrenamientos programados hoy.<button className="sc-quiet" onClick={()=>go('entrenamientos')}>Programar entrenamiento →</button></Empty>}</Card>
 <Card title="Cuotas que necesitan atención" action={<Badge tone={delinquent.length?'red':'green'}>{delinquent.length} alumnos</Badge>}><div className="sc-debt-total"><span>Saldo vencido · {month}</span><strong>{money(overdue.reduce((sum,ch)=>sum+chargeBalance(ch,d.school_payments),0))}</strong></div>{delinquent.slice(0,5).map(id=><div className="sc-list-row" key={id}><span>{d.school_students.find(s=>s.id===id)?.name}</span><strong>{money(overdue.filter(ch=>ch.student_id===id).reduce((n,ch)=>n+chargeBalance(ch,d.school_payments),0))}</strong></div>)}{!delinquent.length&&<Empty>No hay cuotas vencidas registradas para este mes.</Empty>}<button className="sc-primary" onClick={()=>go('cobranzas')}>Ir a cobranzas →</button><p className="sc-hint">Solo cuotas generadas del mes. No incluye las cuotas anteriores por persona.</p></Card></div>
 <div className="sc-overview-grid"><Card title="Categorías de la escuela" action={<button className="sc-quiet" onClick={()=>go('categorias')}>Administrar ↗</button>}>{d.school_categories.filter(c=>c.active).map(cat=>{const n=students.filter(s=>s.category_id===cat.id).length;return <div className="sc-category-line" key={cat.id}><span>{cat.name}<small>{cat.min_age}–{cat.max_age} años · {cat.division}</small></span><div className="sc-meter"><span style={{width:students.length?`${n/students.length*100}%`:'0%'}}/></div><strong>{n}</strong></div>;})}{!d.school_categories.some(c=>c.active)&&<Empty>Configurá las categorías para empezar a inscribir alumnos.</Empty>}</Card><section className="sc-quick-card"><span className="sc-overline">CERCA DE LAS FAMILIAS</span><h2>La comunicación también juega.</h2><p>Recordá actividades, enviá convocatorias y mantené informados a los tutores.</p><button onClick={()=>go('avisos')}>Crear un aviso <ChevronRight size={18}/></button><small>Notificaciones a cuentas y dispositivos habilitados.</small></section></div></>;
}
