import {useState} from 'react';
import {useSchool,Card,Empty,Badge,Editor,Documents,StudentPhoto,selectField,choiceField,save,type Field} from './shared';
import {localDay,seasonAge,eligibleCategories,money} from './metrics.mjs';
const nameField:Field={name:'name',label:'Nombre y apellido',required:true,maxLength:120};
export function Students(){
 const c=useSchool(),d=c.data;const [status,setStatus]=useState('activos'),[filter,setFilter]=useState(''),[search,setSearch]=useState(''),[tab,setTab]=useState('alumnos'),[editor,setEditor]=useState<any>(null),[detail,setDetail]=useState<any>(null);
 const cats=d.school_categories;const people=d.club_people||[];
 const tutorFields:Field[]=[nameField,{name:'birth_date',label:'Fecha de nacimiento del adulto',type:'date',required:true,hint:'El responsable debe tener 18 años o más.'},{name:'phone',label:'Teléfono de emergencia',required:true,maxLength:40},{name:'email',label:'Correo',type:'email',maxLength:254},selectField('person_id','Vincular a una cuenta del padrón (para avisos)',people,false)];
 const fields:Field[]=[nameField,{name:'birth_date',label:'Fecha de nacimiento',type:'date',required:true,max:localDay()},selectField('tutor_id','Adulto responsable',d.school_tutors),choiceField('relationship','Relación con el alumno',['Padre','Madre','Tutor']),{...selectField('category_id','Categoría (vacío = automática por edad)',cats.filter(x=>x.active),false),hint:'Se usa la edad que cumple durante el año. Si coinciden varias divisiones, elegí una.'},{name:'position',label:'Posición preferida',maxLength:80},{name:'active',label:'Alumno activo',type:'checkbox'},{name:'allergies',label:'Alergias',type:'textarea',maxLength:2000},{name:'insurance',label:'Obra social / cobertura',maxLength:200},{name:'valid_until',label:'Vencimiento del apto médico',type:'date'},{name:'notes',label:'Historial médico / observaciones',type:'textarea',maxLength:5000}];
 const selected=d.school_students.find(s=>s.id===detail);
 const rows=d.school_students.filter(s=>(status==='todos'||(status==='activos'?s.active:!s.active))&&(!filter||s.category_id===filter)&&s.name.toLowerCase().includes(search.toLowerCase()));
 return <><div className="sc-section-intro"><div><span className="sc-overline">OPERACIÓN</span><h1>Alumnos y tutores</h1><p>Cada chico, acompañado por un adulto responsable.</p></div><button className="sc-primary" onClick={()=>setEditor({kind:tab==='tutores'?'tutor':'student',row:{active:true}})}>+ {tab==='tutores'?'Nuevo tutor':'Nuevo alumno'}</button></div>
 <div className="sc-tabs"><button aria-pressed={tab==='alumnos'} onClick={()=>setTab('alumnos')}>Alumnos ({d.school_students.filter(s=>s.active).length} activos)</button><button aria-pressed={tab==='tutores'} onClick={()=>setTab('tutores')}>Tutores ({d.school_tutors.length})</button></div>
 {editor&&<Editor key={editor.kind+(editor.row.id||'new')} title={editor.kind==='tutor'?'Ficha del adulto responsable':'Ficha del alumno'} fields={editor.kind==='tutor'?tutorFields:fields} initial={editor.row} onClose={()=>setEditor(null)} onSave={async data=>{await save(editor.kind,data);}}/>}
 {tab==='alumnos'?<Card title="Padrón de alumnos"><div className="sc-toolbar"><label>Buscar<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nombre del alumno"/></label><label>Estado<select value={status} onChange={e=>setStatus(e.target.value)}><option value="activos">Activos</option><option value="inactivos">Inactivos</option><option value="todos">Todos</option></select></label><label>División<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Todas las categorías</option>{cats.map(k=><option value={k.id} key={k.id}>{k.name}</option>)}</select></label></div><div className="sc-table-wrap"><table><thead><tr><th>Alumno</th><th>Categoría</th><th>Responsable</th><th>Estado</th><th>Ficha</th></tr></thead><tbody>{rows.map(s=>{const t=d.school_tutors.find(t=>t.id===s.tutor_id);return <tr key={s.id}><td><div className="sc-person"><span className="sc-avatar">{s.name.split(' ').slice(0,2).map((p:string)=>p[0]).join('')}</span><div><strong>{s.name}</strong><small>Cumple {seasonAge(s.birth_date)} años · {s.position||'Sin posición definida'}</small></div></div></td><td>{cats.find(k=>k.id===s.category_id)?.name}</td><td>{t?.name}<small>{t?.phone} · {s.relationship}</small></td><td><Badge tone={s.active?'green':'neutral'}>{s.active?'Activo':'Inactivo'}</Badge></td><td><button className="sc-quiet" onClick={()=>setDetail(s.id)}>Ver ficha de {s.name}</button><button className="sc-quiet" onClick={()=>setEditor({kind:'student',row:{...s,...d.school_medical.find(m=>m.student_id===s.id)}})}>Editar {s.name}</button></td></tr>;})}</tbody></table></div>{!rows.length&&<Empty>Creá primero una categoría y un tutor; después podrás inscribir al primer alumno.</Empty>}</Card>:<Card title="Adultos responsables"><div className="sc-record-grid">{d.school_tutors.map(t=><article key={t.id} className="sc-person-card"><h3>{t.name}</h3><p>{t.phone}<br/>{t.email||'Sin correo'}</p><p>{d.school_students.filter(s=>s.tutor_id===t.id).length} alumno(s) vinculados</p><Badge tone={t.person_id?'green':'amber'}>{t.person_id?'Cuenta del padrón vinculada':'Sin cuenta para avisos'}</Badge><button className="sc-quiet" onClick={()=>setEditor({kind:'tutor',row:t})}>Editar tutor {t.name}</button></article>)}</div>{!d.school_tutors.length&&<Empty>Agregá el adulto responsable con su teléfono de emergencia.</Empty>}</Card>}
 {selected&&<Card title={'Ficha · '+selected.name} action={<button className="sc-quiet" onClick={()=>setDetail(null)}>Cerrar ficha</button>}><StudentPhoto student={selected.id}/><div className="sc-detail-grid"><div><h3>Datos deportivos</h3><p>Nacimiento: {selected.birth_date}<br/>Categoría: {cats.find(k=>k.id===selected.category_id)?.name}<br/>Posición: {selected.position||'Sin definir'}</p></div><div><h3>Salud · acceso administrativo</h3>{(()=>{const m=d.school_medical.find(m=>m.student_id===selected.id);return <p>Alergias: {m?.allergies||'Sin información cargada'}<br/>Cobertura: {m?.insurance||'Sin información cargada'}<br/>Apto hasta: {m?.valid_until||'Sin vencimiento registrado'}<br/>{m?.notes}</p>;})()}</div></div><Documents student={selected.id}/></Card>}
 </>;
}
export function Categories(){
 const c=useSchool(),[editor,setEditor]=useState<any>(null);
 const fields:Field[]=[{name:'name',label:'Nombre de la categoría',required:true,maxLength:80},{name:'division',label:'División',required:true,maxLength:50},{name:'min_age',label:'Edad mínima que cumple en el año',type:'number',required:true,min:0,max:99},{name:'max_age',label:'Edad máxima que cumple en el año',type:'number',required:true,min:0,max:99},{name:'active',label:'Categoría activa',type:'checkbox'}];
 return <><div className="sc-section-intro"><div><span className="sc-overline">ESCUELA DE FÚTBOL</span><h1>Categorías</h1><p>La asignación automática usa el año de nacimiento y estos rangos.</p></div><button className="sc-primary" onClick={()=>setEditor({division:'Mixta',active:true})}>+ Crear categoría</button></div>{editor&&<Editor key={editor.id||'new'} title="Configurar categoría" fields={fields} initial={editor} onSave={async d=>{await save('category',d);}} onClose={()=>setEditor(null)}/>}<div className="sc-record-grid">{c.data.school_categories.map(k=><Card key={k.id} title={k.name}><Badge tone="green">{k.division}</Badge><p>De {k.min_age} a {k.max_age} años · {k.active?'Activa':'Inactiva'}</p><strong className="sc-big-number">{c.data.school_students.filter(s=>s.category_id===k.id&&s.active).length}</strong><p>alumnos activos</p><button className="sc-quiet" onClick={()=>setEditor(k)}>Editar {k.name}</button></Card>)}</div>{!c.data.school_categories.length&&<Empty>Creá divisiones como Sub-8, Sub-10 o Femenino Sub-12 con sus rangos de edad.</Empty>}</>;
}
export function Staff(){
 const c=useSchool(),d=c.data,[editor,setEditor]=useState<any>(null),[detail,setDetail]=useState('');
 const fields:Field[]=[nameField,{name:'phone',label:'Teléfono',maxLength:40},{name:'email',label:'Correo',type:'email',maxLength:254},{name:'user_id',label:'Cuenta de acceso del profesor',type:'select',options:(d.club_members||[]).filter(m=>['teacher','admin'].includes(m.role)).map(m=>({value:m.user_id,label:m.display_name}))},choiceField('pay_mode','Modalidad de sueldo',['Mensual','Por hora']),{name:'pay_amount',label:'Sueldo mensual o valor por hora (ARS)',type:'number',required:true,min:0,max:100000000,step:'0.01'},{name:'categories',label:'Categorías asignadas',type:'multi',options:d.school_categories.map(k=>({value:k.id,label:k.name}))},{name:'active',label:'Integrante activo',type:'checkbox'}];
 return <><div className="sc-section-intro"><div><span className="sc-overline">EQUIPO</span><h1>Profesores y staff</h1><p>Asignaciones, contacto y documentación profesional.</p></div><button className="sc-primary" onClick={()=>setEditor({active:true,pay_mode:'Mensual',pay_amount:0,categories:[]})}>+ Agregar profesor</button></div>{editor&&<Editor key={editor.id||'new'} title="Ficha del profesor" fields={fields} initial={editor} onSave={async row=>{await save('staff',row);}} onClose={()=>setEditor(null)}/>}<div className="sc-record-grid">{d.school_staff.map(p=>{const pay=d.school_staff_pay.find(x=>x.staff_id===p.id),assign=d.school_assignments.filter(a=>a.staff_id===p.id).map(a=>a.category_id);return <Card key={p.id} title={p.name}><Badge tone={p.active?'green':'neutral'}>{p.active?'Activo':'Inactivo'}</Badge><p>{p.email||'Sin correo'}<br/>{p.phone||'Sin teléfono'}</p><p>{d.school_categories.filter(k=>assign.includes(k.id)).map(k=>k.name).join(' · ')||'Sin categorías asignadas'}</p><p>{pay?.mode}: <strong>{money(pay?.amount||0)}</strong></p><button className="sc-quiet" onClick={()=>setEditor({...p,pay_mode:pay?.mode,pay_amount:pay?.amount,categories:assign})}>Editar {p.name}</button><button className="sc-quiet" onClick={()=>setDetail(p.id)}>Certificaciones de {p.name}</button></Card>;})}</div>{!d.school_staff.length&&<Empty>Cargá el equipo y vinculá sus cuentas de profesor para habilitar el pase de lista.</Empty>}{detail&&<Card title="Currículum y certificaciones" action={<button className="sc-quiet" onClick={()=>setDetail('')}>Cerrar</button>}><Documents staff={detail}/></Card>}</>;
}
