import {useState} from 'react';
import {useSchool,Card,Empty,Badge,Editor,selectField,save,type Field} from './shared';
import {rpc} from '../backend';
import {localDay,clock,minutes,attendanceSummary} from './metrics.mjs';
function plusDay(day:string,n:number){const date=new Date(day+'T12:00:00Z');date.setUTCDate(date.getUTCDate()+n);return date.toISOString().slice(0,10);}
export function Training(){
 const c=useSchool(),d=c.data,[day,setDay]=useState(localDay()),[category,setCategory]=useState(''),[editor,setEditor]=useState<any>(null),[sessionId,setSessionId]=useState('');
 const weekStart=plusDay(day,-((new Date(day+'T12:00:00Z').getUTCDay()+6)%7));const week=Array.from({length:7},(_,i)=>plusDay(weekStart,i));
 const sessions=d.school_sessions.filter(s=>!category||s.category_id===category).sort((a,b)=>a.date.localeCompare(b.date)||a.start_min-b.start_min);
 const current=d.school_sessions.find(s=>s.id===sessionId);
 const fields:Field[]=[{name:'date',label:'Día del entrenamiento',type:'date',required:true},selectField('category_id','Categoría',d.school_categories.filter(k=>k.active)),selectField('staff_id','Profesor responsable',d.school_staff.filter(p=>p.active)),{name:'start',label:'Hora de inicio',type:'time',required:true},{name:'end',label:'Hora de fin',type:'time',required:true},{name:'court',label:'Cancha / espacio',maxLength:80},{name:'plan',label:'Plan de entrenamiento',type:'textarea',maxLength:5000},{name:'cancelled',label:'Sesión cancelada',type:'checkbox'}];
 return <><div className="sc-section-intro"><div><span className="sc-overline">DEPORTIVO</span><h1>Entrenamientos y asistencia</h1><p>Planificá la semana y pasá lista desde la cancha.</p></div>{c.admin&&<button className="sc-primary" onClick={()=>setEditor({date:day,start:'17:00',end:'18:00',cancelled:false})}>+ Programar sesión</button>}</div>
 {editor&&<Editor key={editor.id||'new'} title="Programar entrenamiento" fields={fields} initial={editor} onClose={()=>setEditor(null)} onSave={async row=>{await save('session',{...row,start_min:minutes(row.start),end_min:minutes(row.end)});}}/>}
 <Card title="Agenda semanal"><div className="sc-toolbar"><button className="sc-quiet" aria-label="Semana anterior" onClick={()=>{setDay(plusDay(day,-7));setSessionId('');}}>← Semana anterior</button><label>Fecha<input type="date" value={day} onChange={e=>{if(e.target.value){setDay(e.target.value);setSessionId('');}}}/></label><label>Categoría<select value={category} onChange={e=>{setCategory(e.target.value);setSessionId('');}}><option value="">Todas mis categorías</option>{d.school_categories.map(k=><option value={k.id} key={k.id}>{k.name}</option>)}</select></label><button className="sc-quiet" onClick={()=>{setDay(plusDay(day,7));setSessionId('');}}>Semana siguiente →</button></div><div className="sc-week">{week.map(date=><div className={'sc-day '+(date===day?'selected':'')} key={date}><button className="sc-day-label" onClick={()=>{setDay(date);setSessionId('');}}><span>{new Date(date+'T12:00:00Z').toLocaleDateString('es-AR',{weekday:'short',timeZone:'UTC'})}</span><strong>{date.slice(8)}</strong></button>{sessions.filter(s=>s.date===date).map(s=><button key={s.id} className={'sc-session '+(s.cancelled?'cancelled':'')} onClick={()=>{setDay(date);setSessionId(s.id);}}><strong>{clock(s.start_min)} – {clock(s.end_min)}</strong><span>{d.school_categories.find(k=>k.id===s.category_id)?.name}</span><small>{d.school_staff.find(p=>p.id===s.staff_id)?.name||'Profesor asignado'}</small>{s.cancelled&&<small>Cancelado</small>}</button>)}</div>)}</div><p className="sc-hint">Horarios de Argentina. El cuadrante bloquea superposiciones de profesor y categoría. Las reservas de canchas se gestionan por separado.</p></Card>
 <Card title={'Sesiones del '+new Date(day+'T12:00:00Z').toLocaleDateString('es-AR',{timeZone:'UTC'})}>{sessions.filter(s=>s.date===day).map(s=><div className="sc-list-row" key={s.id}><div><strong>{d.school_categories.find(k=>k.id===s.category_id)?.name}</strong><small>{clock(s.start_min)} – {clock(s.end_min)} · {s.court||'Espacio sin definir'}</small></div><Badge tone={s.cancelled?'neutral':s.plan?'green':'amber'}>{s.cancelled?'Cancelado':s.plan?'Plan cargado':'Sin plan'}</Badge><button className="sc-quiet" onClick={()=>setSessionId(s.id)}>Abrir sesión de {clock(s.start_min)}</button>{c.admin&&<button className="sc-quiet" onClick={()=>setEditor({...s,start:clock(s.start_min),end:clock(s.end_min)})}>Reprogramar</button>}</div>)}{!sessions.some(s=>s.date===day)&&<Empty>No hay entrenamientos para este día.</Empty>}</Card>
 {current&&<Attendance key={current.id} session={current}/>}
 </>;
}
function Attendance({session}:{session:any}){
 const c=useSchool(),d=c.data,existing=d.school_attendance.filter(a=>a.session_id===session.id),roster=d.school_students.filter(s=>s.category_id===session.category_id&&s.active);
 const [draft,setDraft]=useState<Record<string,any>>(Object.fromEntries(existing.map(a=>[a.student_id,{state:a.state,note:a.note}]))),[plan,setPlan]=useState(session.plan),[contacts,setContacts]=useState<any[]>([]);
 const locked=session.cancelled||session.date>localDay();
 return <><Card title={'Plan · '+(d.school_categories.find(k=>k.id===session.category_id)?.name||'Categoría')}><form onSubmit={e=>{e.preventDefault();void c.run(async()=>{await save('plan',{session_id:session.id,plan});await c.refresh();c.notice('Plan de entrenamiento guardado.');});}}><label className="sc-field">Ejercicios, objetivos y materiales<textarea rows={5} value={plan} maxLength={5000} onChange={e=>setPlan(e.target.value)} placeholder="Entrada en calor, definición, táctica…"/></label><button className="sc-primary" disabled={c.busy||session.cancelled}>Guardar plan</button></form></Card>
 <Card title="Pase de lista" action={<Badge tone="green">{roster.length} alumnos</Badge>}>{locked&&<p className="sc-warning">La asistencia se registra desde el día del entrenamiento, en sesiones no canceladas.</p>}<form onSubmit={e=>{e.preventDefault();void c.run(async()=>{const rows=roster.filter(s=>draft[s.id]?.state).map(s=>({student_id:s.id,...draft[s.id]}));await save('attendance',{session_id:session.id,rows});await c.refresh();c.notice('Asistencia guardada. Los alumnos sin marcar no se cuentan como ausentes.');});}}><div className="sc-attendance-list">{roster.map(s=><div key={s.id} className="sc-attendance-row"><strong>{s.name}</strong><label><span className="sc-sr">Estado de {s.name}</span><select aria-label={'Asistencia de '+s.name} disabled={locked||c.busy} value={draft[s.id]?.state||''} onChange={e=>setDraft({...draft,[s.id]:{...draft[s.id],state:e.target.value}})}><option value="" disabled={existing.some(a=>a.student_id===s.id)}>Sin marcar</option><option>Presente</option><option>Ausente</option><option>Justificado</option></select></label><input aria-label={'Observación de '+s.name} placeholder="Observación (opcional)" maxLength={300} value={draft[s.id]?.note||''} disabled={locked||c.busy} onChange={e=>setDraft({...draft,[s.id]:{...draft[s.id],note:e.target.value}})}/></div>)}</div>{!roster.length&&<Empty>Esta categoría no tiene alumnos activos.</Empty>}<button className="sc-primary" disabled={locked||c.busy||!roster.length}>Guardar asistencia</button></form><button className="sc-quiet" onClick={()=>void c.run(async()=>setContacts(await rpc('school_emergency',{p_category:session.category_id})))}>Consultar contactos de emergencia</button>{contacts.map(t=><p key={t.student_id}>{roster.find(s=>s.id===t.student_id)?.name} · {t.tutor_name} ({t.relationship}) · <a href={'tel:'+t.phone}>{t.phone}</a></p>)}</Card></>;
}
